import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import {
  Home,
  Search,
  Settings,
  Code,
  Waypoints,
  CircleUser,
} from 'lucide-react';

import { ScrollArea } from '@/components/ui/scroll-area';

import { Button } from '@/components/ui/button';

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Input } from '@/components/ui/input';
import Link from 'next/link';
import { Separator } from '@/components/ui/separator';
import DynamicBreadcrumb from '@/components/dynamicBreadcrumb';
let mockTopics = [
  { id: 1, name: 'Tech', icon: Code, href: '#' },
  { id: 2, name: 'Game of life', icon: Waypoints, href: '#' },
];
// Make like 50 of these
let mockPosts = [
  { id: 1, title: 'Post 1Some cool text in the title man', href: '#' },
  { id: 2, title: 'Post 2Some cool text in the title man', href: '#' },
  { id: 3, title: 'Post 3Some cool text in the title man', href: '#' },
  { id: 4, title: 'Post 4Some cool text in the title man', href: '#' },
  { id: 5, title: 'Post 5Some cool text in the title man', href: '#' },
  { id: 6, title: 'Post 6Some cool text in the title man', href: '#' },
  { id: 7, title: 'Post 7Some cool text in the title man', href: '#' },
  { id: 8, title: 'Post 8Some cool text in the title man', href: '#' },
  { id: 9, title: 'Post 9Some cool text in the title man', href: '#' },

  { id: 31, title: 'Post 31Some cool text in the title man', href: '#' },
  { id: 32, title: 'Post 32Some cool text in the title man', href: '#' },
  { id: 33, title: 'Post 33Some cool text in the title man', href: '#' },
  { id: 34, title: 'Post 34Some cool text in the title man', href: '#' },
  { id: 35, title: 'Post 35Some cool text in the title man', href: '#' },
  { id: 36, title: 'Post 36Some cool text in the title man', href: '#' },
  { id: 37, title: 'Post 37Some cool text in the title man', href: '#' },
  { id: 38, title: 'Post 38Some cool text in the title man', href: '#' },
  { id: 39, title: 'Post 39Some cool text in the title man', href: '#' },
];

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="fixed inset-0  grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
          <div className=" hidden border-r bg-muted/40 md:block">
            <div className="flex h-full max-h-screen flex-col gap-2">
              <div className="flex h-14 items-center border-b px-4 lg:h-[60px] lg:px-6">
                <Link
                  href="/"
                  className="flex items-center gap-2 font-semibold">
                  <Home className="h-6 w-6" />
                  <span className="">Da blog</span>
                </Link>
                {/* <Button variant="outline" size="icon" className="ml-auto h-8 w-8">
              <Bell className="h-4 w-4" />
              <span className="sr-only">Toggle notifications</span>
            </Button> */}
              </div>
              <div className="flex-1">
                <nav className="grid items-start px-2 gap-3 text-sm font-medium lg:px-4">
                  {mockTopics.map((topic) => (
                    <>
                      <div>
                        <Link
                          key={topic.id}
                          href={topic.href}
                          className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary">
                          <topic.icon className="h-4 w-4" />
                          {topic.name}
                        </Link>
                        <Separator />

                        <ScrollArea className="ml-2 py-1 h-64 w-full rounded-lg ">
                          {mockPosts.map((post) => (
                            <>
                              <Link
                                key={post.id}
                                href={post.href}
                                className="flex ml-4 py-2 text-muted-foreground transition-all hover:text-primary">
                                <span className="">{post.title}</span>
                              </Link>
                            </>
                          ))}
                        </ScrollArea>
                      </div>
                    </>
                  ))}
                </nav>
              </div>
              <div className="mt-auto p-4">
                <Link
                  href="#"
                  className="flex items-center gap-2 px-2 w-full text-lg font-semibold text-muted-foreground md:text-base">
                  <Settings className="h-5 w-5 transition-all " />
                  <span className="">Settings</span>
                </Link>
              </div>
            </div>
          </div>
          <div className="flex flex-col overflow-y-auto">
            <header className="flex h-14 items-center gap-4 border-b bg-muted/40 px-4 lg:h-[60px] lg:px-6">
              <div className="w-full flex-1">
                <form>
                  <div className="relative">
                    <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
                    <Input
                      type="search"
                      placeholder="Search products..."
                      className="w-full appearance-none bg-background pl-8 shadow-none md:w-2/3 lg:w-1/3"
                    />
                  </div>
                </form>
              </div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button
                    variant="secondary"
                    size="icon"
                    className="rounded-full">
                    <CircleUser className="h-5 w-5" />
                    <span className="sr-only">Toggle user menu</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuLabel>My Account</DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>Settings</DropdownMenuItem>
                  <DropdownMenuItem>Support</DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>Logout</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </header>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
